name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CP_ENVIRONMENT: 1 # Environment mode: 0 Development, 1 Github Actions, 2 Production
  CP_ORGANIZATION_SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.CP_ORGANIZATION_SECRETS_MANAGER_ACCESS_TOKEN }}
    
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      src: ${{ steps.filter.outputs.src }}
      test: ${{ steps.filter.outputs.test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'Cargo.toml'
              - 'Dockerfile'
              - '.github/workflows/ci.yml'
              - '.github/workflows/cd.yml'
            test:
              - 'run_tests.sh'
  ci:
    needs: changes
    runs-on: ubuntu-latest

    container: rust:1.72.0
    services:
      rabbitmq:
        image: rabbitmq:3.12
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: guest
          MONGO_INITDB_ROOT_PASSWORD: guest
        ports:
          - 27017:27017
          
    timeout-minutes: 10

    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.test == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'    
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/' Cargo.toml
        env:
          PATCH_VERSION: ${{ github.run_number }}
      - name: Run unit tests
        run: |
          cargo test
      - name: Run integration tests
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          curl -LO https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64
          mv jq-linux-amd64 jq
          chmod +x jq
          export PATH=$PATH:$PWD
          cd ../
          chmod +x run_tests.sh
          ./run_tests.sh
        env:
          CP_ORGANIZATION_AMQP_API_FILE: "./config/actions/amqp_api.json"
          CP_ORGANIZATION_OPENID_CONNECT_CONFIG_FILE: "./config/actions/openid_connect_config.json"